### ISSUE TITLE
insert's optional parameter is not working.

### ISSUE THREAD

**Issue by PrakashThapa** [dkhenry/rethinkjava#10]
I have seen that when we insert simple json, it works, but when we use optional parameter in json like:
`table.insert(json | [json][, {durability: "hard", returnVals: false, upsert: false}])` it produce error: 
`r_str: "Expected 2 argument(s) but found 3."`
the second parameter is also in java Hashmap

**Comment by dkhenry** [comment]
I think I understand the issue, however if you have an actual code sample that causes the problem it will help me track it down. I will start looking into it now.

**Comment by dkhenry** [comment]
So it looks like the way its currently set up none of the optional parameters are working. I will get the fix up now, but it will take some testing before I can release it as a 0.9 release

**Comment by dkhenry** [comment]
I pushed a change that should make it work. I have verified that at a minimum you can write the code that adds those options and they will get passed into the message being sent to the server. There is still lots of testing to be done before I will make it as complete. 

Two tests added so far. Serialization and a general functionality test.

**Comment by PrakashThapa** [comment]
It works with parameters but without parameters it display error as `response {
  type: R_STR
  r_str: "Expected 2 argument(s) but found 1."
}
backtrace {
}
`

**Comment by dkhenry** [comment]
I think I am going to need a code sample to reproduce that. I have it being tested with and without parameters and it is working for me.

**Comment by dkhenry** [comment]
At this point I have the code passing all test cases I current have. I am actively adding new test cases to get better visibility on this, but I haven't turned anything up.

**Comment by PrakashThapa** [comment]
Is it possible to to make new mvn-repo, I mean update. now we have just 0.8 for long time. I dont know  the project creates error if I use source code but completely fine for maven.

**Comment by dkhenry** [comment]
I am working on pushing up the 0.9 release now. I am still not happy with the test coverage, but I think I need to cut the release and move to the next snapshot

**Comment by PrakashThapa** [comment]
I think it's working now. so I am closing this issue.
