### ISSUE TITLE
(may be not Issue) How to Convert cursor of get_all() into Map or list map or json string

### ISSUE THREAD

**Issue by PrakashThapa** [dkhenry/rethinkjava#11]
I have problem to convert value from get_all(array) in string(as json) or Map.

```
 RqlCursor cursor = r.db("test").table("x").get_all(arraylist)
```

when I try to fetch like 

```
for(RqlObject o : cursor) {
        if (o instanceof java.util.List<?>) {
            List<Object> list = o.getList();
          }else if (o instanceof ListIterator<?>) {
            List<Object> list = o.getList();
          }else {
              java.util.Map<String, Object> map = o.getMap();
            }
}
```

None of other instances than `Map` catches above condition and generated error `java.util.ArrayList cannot be cast to java.util.Map` 
How can I get this Object in map or array of list map or even in json formatted string.

**Comment by janih** [comment]
RqlObject o is not instance of List or Map. You can call o.getList in the loop without the instanceof checks.

**Comment by PrakashThapa** [comment]
when I use `o.getList()` in case of  `get_all(..)` it's looks fine, but for same code for `get(..)` it display error: `java.util.HashMap cannot be cast to java.util.List`. How can I identify whether RqlObject  content single object or array of object. When I have `get_all(..)` and print   it display `type: R_ARRAY` and for `get`  it display `type: R_OBJECT
r_object { ...`

**Comment by dkhenry** [comment]
The information your looking for is kept in the getType() method of the private instance member _underlying there is currently no visibility into that, however I can add in some instance methods test the type before its returned.

**Comment by dkhenry** [comment]
What you can do is just call the method as() with a return type of Object such as 

``` java
for(RqlObject c : cursor) {
    Object o = c.as();     
    if (o instanceof java.util.List<?>) {
         List<Object> list = o.getList();
     }else if (o instanceof ListIterator<?>) {
         List<Object> list = o.getList();
     }else {
         java.util.Map<String, Object> map = o.getMap();
     }
}
```

Also I have some test methods added in and a new naked get method that will return object. I am think it would be best to mark as() private

**Comment by PrakashThapa** [comment]
It works. Thank you.
