### ISSUE TITLE
How to implement Lambda function?

### ISSUE THREAD

**Issue by PrakashThapa** [dkhenry/rethinkjava#12]
Sorry Again I am confused because there is no any documentation, I did not find anything, is it already possible to use Lambda function?

**Comment by dkhenry** [comment]
Yes it is. Here is an example on how it should look. 

```
    RqlQuery query = RqlQuery.eval(Arrays.asList(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)).map(     new Function() {


            @Override
            public RqlQuery apply(RqlQuery.Var var1) {
                return var1.add(1);
            }
        });
```

Additionally the function interface with roughly match the official javascript api

**Comment by artichikin** [comment]
Can someone show me how to do a very basic range query? I.e. a query that returns all items with that have someNumberField > 10? It's not clear at all from the API how do do anything except put/set items by key. I'd be happy to submit some example docs once I figure out the basics...

**Comment by dkhenry** [comment]
Here is a short snippet of a range query. 

```
 r.run(r.db(database).table(table).filter( new Function() { 
    @Override
    public RqlQuery apply(RqlQuery.Var var1) { 
        return var.gt(10);
    }
});
```

**Comment by artichikin** [comment]
Thanks Daniel -- I'm still a bit confused though. How do you specify the field that 'var1' is comparing against?

I'm just trying to translate the basic examples from the rethinkdb examples:

So in the this example:

```
table('users').filter(r.row('age').gt(30));
```

Where do you specify the 'age' field below?

```
filter( new Function() { 
    @Override
    public RqlQuery apply(RqlQuery.Var var) { 
        return var.gt(30);
    }
});
```

**Comment by artichikin** [comment]
Sorry to be a pest, but really hope I can get a little help on this -- I'm totally stuck on these basic queries. I promise to pay it forward with some docs & patches!

**Comment by janih** [comment]
Try this:

```
new Function() {
    public RqlQuery apply(Var var) {
        return new GetField(var, "age").gt(30);
    }
}
```

Please ask questions and it would be nice to have better docs :)

**Comment by artichikin** [comment]
Awesome, that works. Thanks!
