### ISSUE TITLE
Exception during insert in case in map exists transformed by google collections2 utility collection

### ISSUE THREAD

**Issue by alexz75** [dkhenry/rethinkjava#15]
**Environment:**
1. OpenJDK 1.7
2. RethinkDB java driver 0.3
3. Guava 17.0

**Run following code:**

```
  RethinkDB rd=RethinkDB.r;
        RethinkDBConnection con = rd.connect("172.16.140.63");
        Map map1=new HashMap();
        map1.put("id", new UUID(221L, 2L).toString());
        Map map2=new HashMap();
        map2.put("ccc", "ddd");

        ArrayList<Map> originalList = Lists.newArrayList(map2,map2);
        Collection<Map> convertedList=Collections2.transform(originalList, new Function<Map, Map>(){

            @Override
            public Map apply(Map f) {
                return f;
            }

        });

        map1.put("innerListOfMap", convertedList);

        rd.table("test").insert(map1,Durability.soft, Boolean.FALSE, Boolean.TRUE).run(con);
        con.close();
```

**Result:** Will throw exception:
com.rethinkdb.RethinkDBException: Unknown Value can't create datatype for : class java.util.HashMap
    at com.rethinkdb.ast.query.RqlUtil.createDatum(RqlUtil.java:149)
    at com.rethinkdb.ast.query.RqlUtil.createDatum(RqlUtil.java:142)
    at com.rethinkdb.ast.query.gen.Datum.toTerm(Datum.java:17)
    at com.rethinkdb.ast.query.RqlQuery.toTerm(RqlQuery.java:86)
    at com.rethinkdb.ast.query.RqlQuery.toTerm(RqlQuery.java:80)
    at com.rethinkdb.ast.query.RqlQuery.toTerm(RqlQuery.java:80)
    at com.rethinkdb.ast.query.RqlQuery.run(RqlQuery.java:95)
    at com.rethinkdb.ast.query.gen.Insert.run(Insert.java:25)
....
**Expected:** I think should not throw exceptions since com.google.common.collect.Collections2$TransformedCollection -regular collection (extends java.util.AbstractCollection)

**Comment by alexz75** [comment]
p.s. for regular ArrayList  same code work as expected

**Comment by janih** [comment]
Your issue might be better suited for https://github.com/npiv/rethink-java-driver :)  probably the problem isn't whether TransformedCollection extends AbstractCollection but the HashMaps inside the TransformedCollection.

**Comment by alexz75** [comment]
My bad, I've opened issue in wrong place
Anyway problem not with HashMaps - I've replaced TransformedCollection with ArrayList and it's ok.
I've already opened issue in right place.
